# Generated by Django 4.2.7 on 2023-12-02 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='aluno',
            old_name='aluno',
            new_name='nome',
        ),
        migrations.AlterField(
            model_name='aluno',
            name='description',
            field=models.TextField(),
        ),
    ]
